#include <assert.h>
#include <stdbool.h>
#include <stdio.h>
#include <string.h>

#include "wiJSON.h"

void testSimpleValues();
void testSimpleArray();
void testSimpleObject();

/* void testObject1();
void testObject2();
void testObject3();
void testObject4(); */

int main() {
	testSimpleValues();
	testSimpleArray();
	testSimpleObject();
	
	/* testObject1();
	testObject2();
	testObject3();
	testObject4(); */

	printf("All tests passed.\n");

	return 0;
}

void testSimpleValues() {
	printf("Testing simple values...\n");
	wiValue* testInt = parseJSON("993214241");
	wiValue* testBool = parseJSON("false");
	wiValue* testString = parseJSON("\"BEGINhiweonfioewfamcl;mkclm oqfnieowq;mfkl;w mfkfo;wqnmcEND\"");
	wiValue* testFloat = parseJSON("-3.21e5");

	assert(testInt->_type == WIINT);
	assert(testInt->contents.intVal == 993214241);

	assert(testBool->_type == WIBOOL);
	assert(testBool->contents.boolVal == false);

	assert(testString->_type == WISTRING);
	assert(strcmp(testString->contents.stringVal, "BEGINhiweonfioewfamcl;mkclm oqfnieowq;mfkl;w mfkfo;wqnmcEND") == 0);

	assert(testFloat->_type == WIFLOAT);
	assert(testFloat->contents.floatVal == -3.21e5);
	printf("Simple tests succeeded.\n");
}

void testSimpleArray() {
	printf("Testing simple array...\n");
	wiValue* testArray = parseJSON(
		"[ 1, -32.4, \"Hello, World!\", true, false, -32e4, null]"
	);

	assert(testArray->_type == WIARRAY);
	assert(testArray->contents.arrayVal != NULL);
	assert(testArray->contents.arrayVal->elementVal != NULL);

	wiArrayEl* currentElement = testArray->contents.arrayVal;

	assert(currentElement != NULL);
	assert(currentElement->elementVal->_type == WIINT);
	assert(currentElement->elementVal->contents.intVal == 1);

	currentElement = currentElement->nextElement;

	assert(currentElement != NULL);
	assert(currentElement->elementVal->_type == WIFLOAT);
	assert(currentElement->elementVal->contents.floatVal == -32.4);

	currentElement = currentElement->nextElement;

	assert(currentElement != NULL);
	assert(currentElement->elementVal->_type == WISTRING);
	assert(strcmp(currentElement->elementVal->contents.stringVal, "Hello, World!") == 0);

	currentElement = currentElement->nextElement;

	assert(currentElement != NULL);
	assert(currentElement->elementVal->_type == WIBOOL);
	assert(currentElement->elementVal->contents.boolVal == true);

	currentElement = currentElement->nextElement;

	assert(currentElement != NULL);
	assert(currentElement->elementVal->_type == WIBOOL);
	assert(currentElement->elementVal->contents.boolVal == false);

	currentElement = currentElement->nextElement;

	assert(currentElement != NULL);
	assert(currentElement->elementVal->_type == WIFLOAT);
	assert(currentElement->elementVal->contents.floatVal == -32e4);

	currentElement = currentElement->nextElement;

	assert(currentElement != NULL);
	assert(currentElement->elementVal->_type == WINULL);
	printf("Simple array test succeeded.\n");
}

void testSimpleObject() {
	// TODO: was generated by ChatGPT, check correctness (seems ok)
	printf("Testing simple objects...\n");

	// Test 1: Simple object with one key-value pair (string)
	wiValue* testObject1 = parseJSON("{ \"key1\": \"value1\" }");
	assert(testObject1->_type == WIPAIR);
	assert(testObject1->contents.pairVal != NULL);

	wiPair* pair1 = testObject1->contents.pairVal;
	assert(strcmp(pair1->key, "key1") == 0);
	assert(pair1->value->_type == WISTRING);
	assert(strcmp(pair1->value->contents.stringVal, "value1") == 0);

	// Test 2: Simple object with multiple key-value pairs (int and string)
	wiValue* testObject2 = parseJSON("{ \"key1\": 42, \"key2\": \"value2\" }");
	assert(testObject2->_type == WIPAIR);
	assert(testObject2->contents.pairVal != NULL);

	wiPair* pair2_kv1 = testObject2->contents.pairVal;
	assert(strcmp(pair2_kv1->key, "key1") == 0);
	assert(pair2_kv1->value->_type == WIINT);
	assert(pair2_kv1->value->contents.intVal == 42);

	wiPair* pair2_kv2 = pair2_kv1->nextPair;
	assert(pair2_kv2 != NULL);
	assert(strcmp(pair2_kv2->key, "key2") == 0);
	assert(pair2_kv2->value->_type == WISTRING);
	assert(strcmp(pair2_kv2->value->contents.stringVal, "value2") == 0);

	// Test 3: Simple object with multiple key-value pairs (float, bool, string)
	wiValue* testObject3 = parseJSON("{ \"key1\": 3.14, \"key2\": true, \"key3\": \"value3\" }");
	assert(testObject3->_type == WIPAIR);
	assert(testObject3->contents.pairVal != NULL);

	wiPair* pair3_kv1 = testObject3->contents.pairVal;
	assert(strcmp(pair3_kv1->key, "key1") == 0);
	assert(pair3_kv1->value->_type == WIFLOAT);
	assert(pair3_kv1->value->contents.floatVal == 3.14);

	wiPair* pair3_kv2 = pair3_kv1->nextPair;
	assert(pair3_kv2 != NULL);
	assert(strcmp(pair3_kv2->key, "key2") == 0);
	assert(pair3_kv2->value->_type == WIBOOL);
	assert(pair3_kv2->value->contents.boolVal == true);

	wiPair* pair3_kv3 = pair3_kv2->nextPair;
	assert(pair3_kv3 != NULL);
	assert(strcmp(pair3_kv3->key, "key3") == 0);
	assert(pair3_kv3->value->_type == WISTRING);
	assert(strcmp(pair3_kv3->value->contents.stringVal, "value3") == 0);

	// Test 4: Simple object with an array and other values
	wiValue* testObject4 = parseJSON("{ \"key1\": [1, 2, 3], \"key2\": false, \"key3\": \"value4\" }");
	assert(testObject4->_type == WIPAIR);
	assert(testObject4->contents.pairVal != NULL);

	wiPair* pair4_kv1 = testObject4->contents.pairVal;
	assert(strcmp(pair4_kv1->key, "key1") == 0);
	assert(pair4_kv1->value->_type == WIARRAY);
	assert(pair4_kv1->value->contents.arrayVal != NULL);

	// Verify array contents [1, 2, 3]
	wiArrayEl* array1 = pair4_kv1->value->contents.arrayVal;
	assert(array1->elementVal->_type == WIINT);
	assert(array1->elementVal->contents.intVal == 1);
	assert(array1->nextElement != NULL);

	wiArrayEl* array2 = array1->nextElement;
	assert(array2->elementVal->_type == WIINT);
	assert(array2->elementVal->contents.intVal == 2);
	assert(array2->nextElement != NULL);

	wiArrayEl* array3 = array2->nextElement;
	assert(array3->elementVal->_type == WIINT);
	assert(array3->elementVal->contents.intVal == 3);

	wiPair* pair4_kv2 = pair4_kv1->nextPair;
	assert(pair4_kv2 != NULL);
	assert(strcmp(pair4_kv2->key, "key2") == 0);
	assert(pair4_kv2->value->_type == WIBOOL);
	assert(pair4_kv2->value->contents.boolVal == false);

	wiPair* pair4_kv3 = pair4_kv2->nextPair;
	assert(pair4_kv3 != NULL);
	assert(strcmp(pair4_kv3->key, "key3") == 0);
	assert(pair4_kv3->value->_type == WISTRING);
	assert(strcmp(pair4_kv3->value->contents.stringVal, "value4") == 0);

	printf("Simple object tests succeeded.\n");
}





